"""Add offers models

Revision ID: e7af82dec41a
Revises:
Create Date: 2026-02-07 15:55:55.826682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.base.models import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = "e7af82dec41a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offers",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("area", sa.Float(), nullable=True),
        sa.Column("rent", sa.Float(), nullable=True),
        sa.Column("admin_fee", sa.Float(), nullable=True),
        sa.Column("utilities", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "offer_sources",
        sa.Column("offer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("OLX", name="offersourcetype", metadata=sa.MetaData()),
            nullable=False,
        ),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("raw_price", sa.JSON(), nullable=True),
        sa.Column("scraped_at", UTCDateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("offer_sources")
    op.drop_table("offers")
    # ### end Alembic commands ###
