"""add offer_raw_infos and extend offers

Revision ID: ecbc5f2f8d2f
Revises: 5036af908fac
Create Date: 2026-02-09 22:45:39.887547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from src.base.models import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "ecbc5f2f8d2f"
down_revision: Union[str, Sequence[str], None] = "5036af908fac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offer_raw_infos",
        sa.Column("offer_source_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column(
            "price_currency",
            sa.Enum("PLN", "EUR", "USD", name="currency", metadata=sa.MetaData()),
            nullable=True,
        ),
        sa.Column("admin_rent", sa.Float(), nullable=True),
        sa.Column(
            "admin_rent_currency",
            sa.Enum("PLN", "EUR", "USD", name="currency", metadata=sa.MetaData()),
            nullable=True,
        ),
        sa.Column("area", sa.Float(), nullable=True),
        sa.Column("rooms", sa.Integer(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("furnished", sa.Boolean(), nullable=True),
        sa.Column("pets_allowed", sa.Boolean(), nullable=True),
        sa.Column("elevator", sa.Boolean(), nullable=True),
        sa.Column("parking", sa.String(), nullable=True),
        sa.Column("building_type", sa.String(), nullable=True),
        sa.Column("photo_urls", sa.JSON(), nullable=True),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("scraped_at", UTCDateTime(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("enriched_address", sa.String(), nullable=True),
        sa.Column("enriched_rent", sa.Float(), nullable=True),
        sa.Column(
            "enriched_rent_currency",
            sa.Enum("PLN", "EUR", "USD", name="currency", metadata=sa.MetaData()),
            nullable=True,
        ),
        sa.Column("enriched_admin_rent", sa.Float(), nullable=True),
        sa.Column(
            "enriched_admin_rent_currency",
            sa.Enum("PLN", "EUR", "USD", name="currency", metadata=sa.MetaData()),
            nullable=True,
        ),
        sa.Column("total_monthly_cost", sa.Float(), nullable=True),
        sa.Column(
            "total_monthly_cost_currency",
            sa.Enum("PLN", "EUR", "USD", name="currency", metadata=sa.MetaData()),
            nullable=True,
        ),
        sa.Column("enriched_at", UTCDateTime(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("geocoded_at", UTCDateTime(), nullable=True),
        sa.Column("maintenance_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            UTCDateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["offer_source_id"],
            ["offer_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("offer_source_id"),
    )
    op.alter_column(
        "offer_sources",
        "raw_price",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.add_column("offers", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column("offers", sa.Column("street_address", sa.String(), nullable=True))
    op.add_column("offers", sa.Column("total_monthly_cost", sa.Float(), nullable=True))
    op.add_column(
        "offers",
        sa.Column(
            "total_monthly_cost_currency",
            sa.Enum("PLN", "EUR", "USD", name="currency"),
            nullable=True,
        ),
    )
    op.add_column("offers", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("offers", sa.Column("longitude", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("offers", "longitude")
    op.drop_column("offers", "latitude")
    op.drop_column("offers", "total_monthly_cost_currency")
    op.drop_column("offers", "total_monthly_cost")
    op.drop_column("offers", "street_address")
    op.drop_column("offers", "summary")
    op.alter_column(
        "offer_sources",
        "raw_price",
        existing_type=sa.JSON(),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_table("offer_raw_infos")
    # ### end Alembic commands ###
